const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const {JSDOM}=require('jsdom');
const dom=new JSDOM('<main id="world"></main><button id="target">Go</button>',{url:'https://example.com',runScripts:'outside-only'}),w=dom.window;
let sound=true,hidden=false,scheduled=new Map(),id=0,contexts=[];
Object.defineProperty(w.document,'hidden',{get:()=>hidden});
w.setTimeout=(fn,ms)=>{scheduled.set(++id,{fn,ms});return id;};w.clearTimeout=i=>scheduled.delete(i);
function param(){return {value:0,setValueAtTime(){},exponentialRampToValueAtTime(){},linearRampToValueAtTime(){},cancelScheduledValues(){},setTargetAtTime(){}};}
class Node {constructor(){this.gain=param();this.frequency=param();this.stopped=false;}connect(n){return n;}disconnect(){}start(){}stop(){this.stopped=true;this.onended?.();}}
class Audio {constructor(){this.state='running';this.currentTime=0;this.sampleRate=100;this.destination={};this.nodes=[];contexts.push(this);}createOscillator(){const n=new Node();this.nodes.push(n);return n;}createGain(){return new Node();}createBiquadFilter(){return new Node();}createBufferSource(){return this.createOscillator();}createBuffer(ch,n){return {getChannelData:()=>new Float32Array(n)};}resume(){this.state='running';return Promise.resolve();}suspend(){this.state='suspended';return Promise.resolve();}close(){this.state='closed';}}
w.AudioContext=Audio;w.eval(fs.readFileSync(require('node:path').resolve(__dirname,'../games/adventure/delight.js'),'utf8').replace(/\bexport /g,'')+'\nwindow.effects={createDelight,burst,livingWorld,foxPortrait};');
const joy=w.effects.createDelight({soundEnabled:()=>sound,motionEnabled:()=>true});joy.setScene('map');assert.equal(contexts.length,0,'ambience must wait for user interaction');joy.gesture();assert.equal(contexts.length,1);assert(joy.ambientScheduled);const first=contexts[0];assert(first.nodes.length>4,'ambient phrase should contain surf, birds and notes');
joy.setScene('quest');assert(!joy.ambientScheduled,'no ambient loop during challenges');joy.effect('correct');joy.note(2);joy.drum(0);joy.drum(1);joy.drum(2);assert(first.nodes.length>10);
sound=false;joy.sync();assert.equal(first.state,'suspended');assert(first.nodes.every(n=>n.stopped),'mute must stop scheduled and active voices');const before=first.nodes.length;joy.effect('finish');joy.note(4);joy.drum(0);assert.equal(first.nodes.length,before,'muted controls must not create audio');
sound=true;joy.setScene('map');joy.sync();assert(joy.ambientScheduled);hidden=true;w.document.dispatchEvent(new w.Event('visibilitychange'));assert(!joy.ambientScheduled);assert.equal(first.state,'suspended');hidden=false;w.document.dispatchEvent(new w.Event('visibilitychange'));assert(joy.ambientScheduled);assert.equal(first.state,'running');
w.effects.livingWorld(w.document.querySelector('main'));assert.equal(w.document.querySelectorAll('.firefly').length,16);assert.equal(w.document.querySelector('.living-world').getAttribute('aria-hidden'),'true');w.effects.burst(w.document.querySelector('button'),{motion:false});assert.equal(w.document.querySelectorAll('.joy-burst').length,0);w.effects.burst(w.document.querySelector('button'),{motion:true,big:true});assert.equal(w.document.querySelectorAll('.joy-burst i').length,22);joy.destroy();assert(!joy.ambientScheduled);assert.equal(first.state,'closed');console.log('PASS: gesture-only ambience, musical effects, mute, hidden-tab pause/resume, scene cleanup, reduced-motion particles, decorative accessibility.');
