import {createEntrance} from './entrance.js?v=4';
import {createDelight,burst,livingWorld,foxPortrait} from './delight.js?v=2';
import {regions,quests,challenges,ui,text} from './content.js';
import {SAVE_KEY,fresh,normalize,completedCount,lightCount,totalStars,unlocked,award} from './state.js?v=2';
const $=s=>document.querySelector(s),app=$('#app'),dialog=$('#dialog');
let storageOK=true,state;try{state=normalize(JSON.parse(localStorage.getItem(SAVE_KEY)));if(!localStorage.getItem(SAVE_KEY)){state.lang=localStorage.getItem('seanGameLang')==='en'?'en':'es';}}catch{state=fresh();}
let screen='entry',entrance=null,timers=[],audioContext,run=0,solved=false,currentTask=null,playing=false,returnFocus=null;
const tr=x=>typeof x==='string'?x:x?.[state.lang]||'';
const t=k=>tr(ui[k]);
const el=(tag,cls,txt)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(txt!==undefined)n.textContent=tr(txt);return n;};
const button=(label,cls,action)=>{const b=el('button',cls,label);b.type='button';if(action)b.onclick=(event)=>{joy.gesture();if(!b.classList.contains('sound-toggle')&&!b.classList.contains('note-key')&&!b.classList.contains('beat-cell'))joy.effect('tap');if(!b.classList.contains('map-pin'))burst(b,{motion:motionOn()});action(event);};return b;};
const motionOn=()=>state.motion&&!matchMedia('(prefers-reduced-motion: reduce)').matches;
const joy=createDelight({soundEnabled:()=>state.sound,motionEnabled:motionOn});
function save(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));localStorage.setItem('seanGameLang',state.lang);storageOK=true;}catch{storageOK=false;}}
function later(fn,ms){const r=run;const id=setTimeout(()=>{if(r===run)fn();},ms);timers.push(id);return id;}
function clean(){document.body.classList.remove('arriving-world');entrance?.dispose();entrance=null;run++;timers.forEach(clearTimeout);timers=[];playing=false;try{speechSynthesis.cancel();}catch{}solved=false;currentTask=null;}
function speak(message){if(!state.sound||!('speechSynthesis'in window))return;try{speechSynthesis.cancel();joy.duck();const u=new SpeechSynthesisUtterance(tr(message));u.lang=state.lang==='es'?'es-ES':'en-US';u.rate=.9;speechSynthesis.speak(u);}catch{}}
function tone(note=0,length=.2,kind='sine'){joy.note(note,length,kind);}
function chime(){joy.effect('correct');}
function confetti(){if(!motionOn())return;for(let i=0;i<30;i++){const c=el('i','confetti');c.style.left=`${Math.random()*100}%`;c.style.background=['#f6cb74','#8cae90','#d7a1a8','#b5a7d3'][i%4];c.style.animationDelay=`${Math.random()*.5}s`;document.body.append(c);setTimeout(()=>c.remove(),3200);}}
let toastTimer;function toast(msg){$('#toast').textContent=tr(msg);clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').textContent='',3300);}
function modal(title,body,actions,portrait){returnFocus=document.activeElement;dialog.replaceChildren();if(portrait){const face=el('div','portrait',portrait==='🦊'?'':portrait);if(portrait==='🦊')face.append(foxPortrait());dialog.append(face);}const h=el('h2','',title);h.id='dialog-title';dialog.append(h);if(typeof body==='string'||body?.es)dialog.append(el('p','',body));else dialog.append(body);const row=el('div','dialog-actions');for(const [label,fn,cls]of actions)row.append(button(label,cls||'primary',()=>{dialog.close();fn?.();}));dialog.append(row);if(!dialog.open)dialog.showModal();}
dialog.addEventListener('close',()=>{if(returnFocus?.isConnected)returnFocus.focus();});
function help(){modal(t('help'),t('helptext'),[[t('close')]],'🧭');}
function header(){const h=el('header','topbar'),brand=el('div','brand');brand.innerHTML='<span class="brand-mark" aria-hidden="true">✦</span>';const name=el('div','',t('title'));name.append(el('small','',t('subtitle')));brand.append(name);h.append(brand);const tools=el('div','tools'),langs=el('div','lang');for(const l of ['es','en']){const b=button(l.toUpperCase(),l===state.lang?'active':'',()=>{state.lang=l;save();render();});b.setAttribute('aria-pressed',String(l===state.lang));langs.append(b);}tools.append(langs);const sound=button(state.sound?'♫':'♪','sound-toggle',()=>{state.sound=!state.sound;joy.sync();save();if(!state.sound){try{speechSynthesis.cancel();}catch{}}sound.textContent=state.sound?'♫':'♪';sound.setAttribute('aria-pressed',String(state.sound));});sound.setAttribute('aria-label',t('sound'));sound.setAttribute('aria-pressed',String(state.sound));tools.append(sound);const motion=button(state.motion?'✧':'·','motion-toggle',()=>{state.motion=!state.motion;save();document.body.classList.toggle('calm-motion',!state.motion);motion.textContent=state.motion?'✧':'·';motion.setAttribute('aria-pressed',String(state.motion));});motion.setAttribute('aria-label',tr(text('Animaciones','Animations')));motion.setAttribute('aria-pressed',String(state.motion));tools.append(motion);const hb=button('?','',help);hb.setAttribute('aria-label',t('help'));tools.append(hb);h.append(tools);return h;}
function render(){clean();document.documentElement.lang=state.lang;document.body.classList.toggle('calm-motion',!state.motion);const atEntrance=screen==='entry'||!state.started;document.body.dataset.scene=atEntrance?'entry':screen;joy.setScene(atEntrance?'welcome':screen);app.replaceChildren(header());if(atEntrance)welcome();else if(screen==='quest'&&state.active)questView();else if(screen==='ending')ending();else worldView();window.scrollTo({top:0,behavior:'instant'});}
function welcome(){
 const returning=state.started,section=el('main','welcome world-entry'),copy=el('div','welcome-copy');
 copy.append(el('div','eyebrow',returning?text('Tu isla te estaba esperando','Your island has been waiting'):text('Al otro lado del mar, empieza tu historia','Across the sea, your story begins')));
 const h=el('h1','',t('title'));h.append(el('em','',t('subtitle')));copy.append(h,el('p','',returning?text('Pip guardó tu lugar. Las luces, tus amigos y una nueva aventura te esperan.','Pip saved your place. The lights, your friends, and a new adventure are waiting.'):text('Sigue la luz. Cruza el mar. Hay un mundo entero esperando conocerte.','Follow the light. Cross the sea. A whole world is waiting to meet you.')));
 const enter=button(returning?text('Volver a mi isla','Return to my island'):text('Entrar en la aventura','Enter the adventure'),'primary enter-world',arrive);
 copy.append(enter,el('p','welcome-foot',text('Un toque. Y ya estás en otro mundo.','One tap. A whole new world.')));
 const guide=el('div','arrival-guide');guide.append(foxPortrait(),el('span','',text('¡Por aquí!','This way!')));section.append(copy,guide);
 const travel=el('div','arrival-caption');travel.hidden=true;travel.setAttribute('role','status');travel.append(el('span','arrival-orbit','✦'),el('p','',text('El puerto está cerca…','The harbor is just ahead…')));section.append(travel);
 const skip=button(text('Saltar llegada','Skip arrival'),'skip-arrival',()=>entrance?.skip());skip.hidden=true;section.append(skip);app.append(section);
 entrance=createEntrance(section,{motion:motionOn,label:tr(text('Una isla tridimensional con mar, nubes, casas, barcos y un faro.','A three-dimensional island with an ocean, clouds, cottages, boats, and a lighthouse.'))});
 let entering=false;
 function arrive(){if(entering)return;entering=true;enter.disabled=true;section.classList.add('arriving');document.body.classList.add('arriving-world');skip.hidden=false;travel.hidden=false;skip.focus({preventScroll:true});joy.effect('arrival');entrance.flyIn(()=>{document.body.classList.remove('arriving-world');state.started=true;save();screen='map';render();chime();if(!returning)story(0,()=>startQuest(quests[0]));});}
}
function story(ri,go){joy.effect('friend');state.seen.push(ri);save();const r=regions[ri];modal(r.name,r.intro,[[text('¡Vamos!','Let’s go!'),go]],r.animal);speak(r.intro);}
function nextQuest(){return quests[completedCount(state)]||quests[0];}
function continueQuest(){if(state.active){screen='quest';render();return;}const q=nextQuest();if(!state.seen.includes(q.region))story(q.region,()=>startQuest(q));else startQuest(q);}
function worldView(){const layout=el('main','layout'),main=el('section','main-column');const heading=el('div','page-heading'),title=el('div');title.append(el('p','eyebrow',text('Tu pequeño mundo de grandes cosas','Your little world of wonderful things')),el('h1','',screen==='journal'?t('journal'):screen==='home'?t('home'):screen==='studio'?t('studio'):t('map')),el('p','',screen==='map'?t('choose'):text('Cada pequeño paso cuenta.','Every little step matters.')));heading.append(title,el('span','weather',text('☀ Un buen día para explorar','☀ A lovely day to explore')));main.append(heading);
 if(screen==='map')drawMap(main);else if(screen==='journal')journal(main);else if(screen==='home')cottage(main);else if(screen==='studio'){const panel=el('div','activity');main.append(panel);studio(panel,false);}
 const nav=el('nav','nav');nav.setAttribute('aria-label',tr(text('Explorar la aventura','Explore the adventure')));[['map','⌘'],['journal','▤'],['home','⌂'],['studio','♫']].forEach(([key,icon])=>nav.append(button(`${icon}  ${t(key)}`,key===screen?'active':'',()=>{screen=key;render();})));main.append(nav);layout.append(main,sidebar());app.append(layout);const foot=el('footer','footer');const a=el('a','','SeanAli.online');a.href='/';foot.append(a,document.createTextNode(' · '+tr(text('Hecho para explorar con calma.','Made for unhurried adventures.'))));app.append(foot);}
function drawMap(main){const frame=el('div','map-frame'),img=el('img','map-art');img.src='/games/adventure/island.webp';img.alt=tr(text('Una isla con puerto, huerto, selva, pueblo musical, jardín y faro.','An island with a harbor, orchard, jungle, music village, garden, and lighthouse.'));frame.append(img);livingWorld(frame);regions.forEach((r,i)=>{const completed=lightCount(state)>i,isOpen=lightCount(state)>=i;const aura=el('div',completed?'region-aura restored':'region-aura');aura.style.left=r.xy[0]+'%';aura.style.top=r.xy[1]+'%';frame.append(aura);const pin=button('',`map-pin ${completed?'restored':isOpen?'current':'locked'}`,()=>regionDialog(i));pin.style.left=r.xy[0]+'%';pin.style.top=r.xy[1]+'%';pin.setAttribute('aria-label',`${tr(r.name)} — ${completed?tr(r.restored):isOpen?tr(text('Explorar','Explore')):tr(text('Cerrado','Locked'))}`);pin.append(el('span','pin-icon',completed?'✓':isOpen?'✦':'·'),el('span','pin-label',r.name));frame.append(pin);});
 [[10,83],[40,54],[39,21],[84,43],[89,80],[58,36]].forEach(([x,y],i)=>{if(state.discovered.includes(i)||lightCount(state)<i)return;const s=button('✧','spark',()=>{state.discovered.push(i);save();joy.effect('treasure');burst(s,{motion:motionOn(),big:true});toast(text('¡Encontraste una concha de luz!','You found a starlight shell!'));s.remove();const stat=$('#shell-stat');if(stat)stat.textContent=`🐚 ${state.discovered.length}/6`;});s.style.left=x+'%';s.style.top=y+'%';s.setAttribute('aria-label',tr(text('Recoger concha de luz','Collect starlight shell')));frame.append(s);});
 const caption=el('div','map-caption');caption.append(el('span','',text('ARCHIPIÉLAGO DE LOS PEQUEÑOS MILAGROS','THE ISLES OF LITTLE WONDERS')));frame.append(caption);main.append(frame);const legend=el('div','map-legend');legend.append(el('b','',text('✦ Sigue la luz dorada','✦ Follow the golden light')),el('span','',text('Busca pequeños destellos…','Look for little glimmers…')));main.append(legend);const list=el('div','region-list');regions.forEach((r,i)=>{const b=button('','',()=>regionDialog(i));b.append(el('span','region-icon',r.icon));const txt=el('span');txt.append(el('b','',r.name),el('small','',lightCount(state)>i?tr(r.restored):`${quests.filter(q=>q.region===i&&state.completed[q.id]).length}/8 ${tr(text('misiones','quests'))}`));b.append(txt);list.append(b);});main.append(list);}
function sidebar(){const aside=el('aside','side'),pc=el('div','progress-card');pc.append(el('div','eyebrow',text('LA LUZ PERDIDA','THE LOST LIGHT')),el('h2','',text('Un faro. Seis luces.','One lighthouse. Six lights.')));const lights=el('div','lights');for(let i=0;i<6;i++)lights.append(el('span',`light ${i<lightCount(state)?'on':''}`,'✦'));pc.append(lights);const track=el('div','progress-track'),fill=el('i');fill.style.width=completedCount(state)/48*100+'%';track.append(fill);pc.append(track);const small=el('div','progress-small');small.append(el('span','',`${lightCount(state)}/6 ${t('lights')}`),el('span','',`${completedCount(state)}/48 ${tr(text('misiones','quests'))}`));pc.append(small);aside.append(pc);
 const buddy=el('div','companion'),q=nextQuest(),r=regions[q.region];buddy.append(el('div','companion-avatar',r.animal),el('div','name',r.friend+tr(text(' · TU COMPAÑERO',' · YOUR COMPANION'))),el('p','',completedCount(state)===48?t('finaltext'):state.active?text('¡Aquí estás! Guardé nuestro lugar. ¿Seguimos?','You’re here! I saved our place. Shall we keep going?'):r.intro),el('small','',completedCount(state)===48?text('¡Toda la isla te espera!','The whole island is yours!'):`${t('quest')} ${completedCount(state)+1} · ${tr(q.name)}`));const avatar=buddy.querySelector('.companion-avatar');if(r.animal==='🦊'){avatar.replaceChildren(foxPortrait());}avatar.append(button('♡','pet-friend',()=>{joy.effect('friend');buddy.classList.remove('friend-happy');void buddy.offsetWidth;buddy.classList.add('friend-happy');toast(text('¡Qué alegría verte!','So happy to see you!'));}));avatar.querySelector('button').setAttribute('aria-label',tr(text('Saludar a tu amigo','Say hello to your friend')));buddy.append(button(completedCount(state)===48?text('Ver nuestro final','See our ending'):t('continue'),'primary',()=>{if(completedCount(state)===48){screen='ending';render();}else continueQuest();}));aside.append(buddy);const stats=el('div','stat-line');stats.append(el('span','',`✦ ${totalStars(state)} ${t('stars')}`));const shells=el('span','',`🐚 ${state.discovered.length}/6`);shells.id='shell-stat';stats.append(shells);aside.append(stats,el('p','save-note',storageOK?t('saved'):t('nosave')));return aside;}
function regionDialog(i){const r=regions[i],body=el('div');if(lightCount(state)<i){modal(r.name,t('locked'),[[t('close')]],r.icon);return;}body.append(el('p','',lightCount(state)>i?r.restored:r.intro));const list=el('div','quest-list');quests.filter(q=>q.region===i).forEach(q=>{const idx=quests.indexOf(q),done=state.completed[q.id];const b=button('','quest-row '+(!done&&unlocked(state,idx)?'current':''),()=>{dialog.close();startQuest(q);});b.disabled=!unlocked(state,idx);b.append(el('span','',done?'✓':String(q.index+1)),el('span','',q.name),el('small','',done?'★'.repeat(done):!b.disabled?'→':'·'));list.append(b);});body.append(list);modal(r.name,body,[[t('back'),null,'soft']],r.animal);}
function startQuest(q){joy.effect('travel');const idx=quests.indexOf(q);if(!unlocked(state,idx))return;if(state.active&&state.active.id!==q.id){modal(text('¿Cambiar de misión?','Switch quests?'),text('Esta misión volverá a empezar. Tus premios siguen guardados.','This quest will restart. Your earned rewards stay saved.'),[[text('Seguir aquí','Stay here'),()=>{screen='quest';render();}],[text('Cambiar','Switch'),()=>{state.active={id:q.id,stage:0,mistakes:0};save();screen='quest';render();},'soft']]);return;}state.active??={id:q.id,stage:0,mistakes:0};save();screen='quest';render();}
function questView(){const q=quests.find(q=>q.id===state.active.id),r=regions[q.region],task=challenges(q)[state.active.stage];currentTask=task;const shell=el('main','quest-shell'),top=el('div','quest-top');const back=button('←','soft',()=>{screen='map';save();render();});back.setAttribute('aria-label',t('back'));top.append(back);const track=el('div','track');track.append(el('p','',`${tr(r.name)} · ${tr(q.name)} · ${state.active.stage+1}/3`));const steps=el('div','steps');for(let i=0;i<3;i++)steps.append(el('i',i<=state.active.stage?'on':''));track.append(steps);top.append(track);shell.append(top);const panel=el('section','activity');panel.style.setProperty('--region-color',r.color);const friend=el('div','quest-friend');if(r.animal==='🦊')friend.append(foxPortrait());else friend.append(el('span','creature',r.animal));panel.append(friend);panel.append(el('div','eyebrow',`${r.animal} ${r.friend} · ${t('quest')} ${q.index+1}`));const h=el('h1','',task.prompt);h.tabIndex=-1;panel.append(h);const goals=[text('Ayuda a Pip a reparar el puerto.','Help Pip repair the harbor.'),text('Prepara el mercado con Mila.','Help Mila get the market ready.'),text('Ayuda a Ollie a cuidar la selva.','Help Ollie care for the jungle.'),text('Devuelve la canción al pueblo de Luna.','Bring the song back to Luna’s village.'),text('Ayuda a Sol a llenar el jardín de amistad.','Help Sol fill the garden with friendship.'),text('Lleva nuestras luces hasta el faro.','Bring our lights to the lighthouse.')];panel.append(el('p','mission-goal',goals[q.region]));const controls=el('div','activity-tools');controls.append(button('♫ '+t('listen'),'soft',()=>speak(task.prompt)));panel.append(controls);if(task.scene)panel.append(el('div','scene',task.scene));const target=el('div');target.id='challenge';panel.append(target);const feedback=el('div','feedback');feedback.id='feedback';feedback.setAttribute('aria-live','polite');panel.append(feedback);shell.append(panel);app.append(shell);
 ({choice:choices,order:ordering,spell:spelling,memory:matching,tune:melody,rhythm:rhythm,drive:driving,studio:()=>studio(target,true),lantern:lanterns}[task.type])(target,task);h.focus({preventScroll:true});}
function wrong(hint){if(solved)return;if(state.active){state.active.mistakes++;save();}joy.effect('wrong');const panel=$('.activity');if(panel){panel.classList.remove('try-again');void panel.offsetWidth;panel.classList.add('try-again');}speak(ui.wrong);const fb=$('#feedback');if(fb)fb.textContent=tr(hint||ui.wrong);}
function win(){if(solved)return;solved=true;chime();speak(ui.correct);const panel=$('.activity');panel?.classList.add('is-success');burst($('#challenge'),{motion:motionOn(),big:true});const stars=el('div','success-stars','✦ ✦ ✦');stars.setAttribute('aria-hidden','true');$('#feedback').before(stars);const fb=$('#feedback');fb.replaceChildren(el('span','',t('correct')));const next=button(t('next')+' →','primary',advance);fb.append(next);next.focus({preventScroll:true});}
function advance(){if(!solved||!state.active)return;const q=quests.find(q=>q.id===state.active.id);if(state.active.stage<2){state.active.stage++;save();render();}else{const first=!state.completed[q.id],rank=award(state,q.id,state.active.mistakes);save();clean();app.replaceChildren(header());const c=el('main','celebration');c.append(el('div','trophy',q.index===7?regions[q.region].gift:'✦'),el('p','eyebrow',regions[q.region].name),el('h1','',q.index===7?t('chapterDone'):t('done')),el('p','',q.name),el('div','earned','★'.repeat(rank)+'☆'.repeat(3-rank)),el('p','',q.index===7?regions[q.region].outro:text('Un paso más. La isla despierta contigo.','One more step. The island is waking up with you.')));c.append(button(q.id===quests[47].id?t('next'):t('back'),'primary',()=>{screen=q.id===quests[47].id?'ending':'map';render();}));app.append(c);screen='reward';joy.setScene('reward');if(first)confetti();joy.effect('finish');window.scrollTo(0,0);}}
function shuffle(a){const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]];}return b;}
function choices(target,task){const list=el('div','answers');shuffle(task.options.map((label,i)=>({label,i}))).forEach((o,k)=>{const b=button('','answer',()=>{if(solved)return;if(o.i===task.correct){b.classList.add('good');list.querySelectorAll('button').forEach(x=>x.disabled=true);win();}else{b.classList.add('bad');b.disabled=true;wrong(task.hint);}});b.append(el('span','letter',String.fromCharCode(65+k)),el('span','',o.label));list.append(b);});target.append(list);}
function ordering(target,task){const reminder=el('p','',task.prompt.es.includes('trabalenguas')?task.items.map(tr).join(' '):tr(text('Toca las piezas en orden.','Tap the pieces in order.')));target.append(reminder);const seq=el('div','sequence'),tokens=el('div','tokens');target.append(seq,tokens);let next=0;shuffle(task.items.map((label,i)=>({label,i}))).forEach(o=>{const b=button(o.label,'token',()=>{if(solved)return;if(o.i!==next){wrong(text('Busca qué viene primero.','Look for what comes first.'));return;}tone(next);b.disabled=true;seq.append(el('span','',o.label));next++;if(next===task.items.length)win();});tokens.append(b);});}
function spelling(target,task){target.append(el('p','',task.word));const seq=el('div','sequence'),tokens=el('div','tokens');target.append(seq,tokens);let next=0;shuffle([...task.word].map((label,i)=>({label,i}))).forEach(o=>{const b=button(o.label,'token',()=>{if(solved)return;if(o.label!==task.word[next]){wrong(text('Mira la palabra. Busca la siguiente letra.','Look at the word. Find the next letter.'));return;}tone(next%5);b.disabled=true;seq.textContent+=o.label;next++;if(next===task.word.length)win();});tokens.append(b);});const hear=button(text('♫ Oír la palabra en inglés','♫ Hear the English word'),'soft',()=>{if(!state.sound||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(task.word);u.lang='en-US';u.rate=.8;speechSynthesis.speak(u);});target.append(hear);}
function matching(target,task){const icons=['🦋','🍊','🌸','🐚','🌿'],deck=shuffle(icons.slice(0,task.pairs).flatMap((v,i)=>[{v,p:i},{v,p:i}])),grid=el('div','memory-grid');let open=[],pairs=0,busy=false;deck.forEach((card,i)=>{const b=button('✦','memory-tile',()=>{if(busy||b.disabled||solved||open.some(x=>x.i===i))return;b.textContent=card.v;b.classList.add('open');b.setAttribute('aria-label',card.v);tone(i%5);open.push({b,card,i});if(open.length===2){if(open[0].card.p===open[1].card.p){open.forEach(x=>{x.b.disabled=true;x.b.classList.add('matched');});burst(open[1].b,{motion:motionOn()});joy.effect('pair');open=[];pairs++;if(pairs===task.pairs)win();}else{busy=true;later(()=>{open.forEach(x=>{x.b.textContent='✦';x.b.classList.remove('open');x.b.setAttribute('aria-label',tr(text('Carta','Card'))+' '+(x.i+1));});open=[];busy=false;},800);}}});b.setAttribute('aria-label',tr(text('Carta','Card'))+' '+(i+1));grid.append(b);});target.append(grid);}
function melody(target,task){patternGame(target,task.notes,['Do','Re','Mi','Sol','La']);}
function rhythm(target,task){patternGame(target,task.pattern,['●','◆','▲'],true);}
function patternGame(target,pattern,labels,drum=false){let pos=0,ready=false;const status=el('div','sequence',text('Primero toca Escuchar.','Tap Listen first.')),keys=el('div','note-keys');target.append(status);const replay=button('▶ '+t('listen'),'soft',playPattern);target.append(replay,keys);const bs=labels.map((label,i)=>{const b=button(label,'note-key',()=>{if(solved||!ready||playing)return;drum?joy.drum(i):tone(i,.35);b.classList.remove('note-hit');void b.offsetWidth;b.classList.add('note-hit');if(pattern[pos]!==i){wrong(text('Escucha el patrón otra vez.','Listen to the pattern again.'));pos=0;ready=false;status.textContent=tr(text('Toca Escuchar para volver a oírlo.','Tap Listen to hear it again.'));return;}pos++;status.textContent=`${pos} / ${pattern.length}`;if(pos===pattern.length)win();});b.setAttribute('aria-label',tr(text('Nota','Note'))+' '+label);keys.append(b);return b;});
 function playPattern(){if(playing||solved)return;playing=true;ready=false;pos=0;replay.disabled=true;status.textContent=tr(text('Mira y escucha…','Watch and listen…'));pattern.forEach((n,i)=>later(()=>{bs[n].classList.add('lit');drum?joy.drum(n):tone(n,.35);status.textContent=labels[n];later(()=>bs[n].classList.remove('lit'),360);},i*600));later(()=>{playing=false;ready=true;replay.disabled=false;status.textContent=tr(text('¡Tu turno!','Your turn!'));},pattern.length*600+150);}}
function driving(target,task){let step=0,green=false,busy=false;const traffic=el('div','traffic'),light=el('span','traffic-light'),label=el('span','',text('ROJO · Espera','RED · Wait'));traffic.append(light,label);target.append(traffic);const road=el('div','road'),path=el('div','road-path');road.append(path);target.append(road);const controls=el('div','drive-controls');const wait=button(text('Esperar','Wait'),'soft',()=>{if(solved||busy)return;if(green){toast(text('Está verde. Puedes avanzar.','It is green. You can move.'));return;}busy=true;label.textContent=tr(text('Mira a ambos lados…','Look both ways…'));later(()=>{green=true;busy=false;light.classList.add('green');label.textContent=tr(text('VERDE · Avanza','GREEN · Go'));tone(2);},500);});const go=button(text('Avanzar →','Go →'),'primary',()=>{if(solved||busy)return;if(!green){wrong(text('Con rojo esperamos. Toca Esperar.','We wait on red. Tap Wait.'));return;}step++;joy.effect('drive');green=false;light.classList.remove('green');label.textContent=tr(text('ROJO · Espera','RED · Wait'));draw();if(step===task.length){go.disabled=true;wait.disabled=true;win();}});controls.append(wait,go);target.append(controls);function draw(){if(!path.children.length){for(let i=0;i<=task.length;i++)path.append(el('span','road-stop',i===task.length?'🏁':'·'));const car=el('b','moving-car','🚙');car.setAttribute('aria-hidden','true');path.append(car);}path.querySelector('.moving-car').style.left=`calc(${step/task.length*100}% - ${step/task.length*32}px)`;road.setAttribute('aria-label',`${step} / ${task.length}`);}draw();}
function studio(target,isQuest){let grid=el('div','studio-grid'),step=0,playId=0;target.append(el('p','',text('Toca las casillas. Escucha tu canción.','Tap the squares. Hear your song.')));const sounds=['●','◆','▲'];state.song.forEach((on,i)=>{const b=button(on?sounds[Math.floor(i/8)]:'·',`beat-cell ${on?'on':''}`,()=>{state.song[i]=!state.song[i];b.classList.toggle('on',state.song[i]);b.textContent=state.song[i]?sounds[Math.floor(i/8)]:'·';b.setAttribute('aria-pressed',String(state.song[i]));save();if(state.song[i])joy.drum(Math.floor(i/8));});b.setAttribute('aria-label',`${tr(text('Instrumento','Instrument'))} ${Math.floor(i/8)+1}, ${tr(text('paso','step'))} ${i%8+1}`);b.setAttribute('aria-pressed',String(on));grid.append(b);});target.append(grid);const controls=el('div','activity-tools'),play=button(text('▶ Escuchar','▶ Play'),'primary',()=>{if(playing){playing=false;playId++;grid.querySelectorAll('.playing').forEach(b=>b.classList.remove('playing'));play.textContent=tr(text('▶ Escuchar','▶ Play'));return;}if(!state.song.some(Boolean)){toast(text('Añade al menos una nota.','Add at least one note.'));return;}playing=true;step=0;play.textContent=tr(text('■ Parar','■ Stop'));tick(++playId);});controls.append(play);target.append(controls);
 function tick(id){if(!playing||id!==playId)return;[...grid.children].forEach((b,i)=>{b.classList.toggle('playing',i%8===step);if(i%8===step&&state.song[i])joy.drum(Math.floor(i/8));});step=(step+1)%8;later(()=>tick(id),300);}
 if(isQuest)target.append(button(text('Guardar nuestra canción','Save our song'),'soft',()=>{if(state.song.filter(Boolean).length<3){toast(text('Añade tres notas para nuestra canción.','Add three notes for our song.'));return;}playing=false;save();win();}));else target.append(el('p','save-note',t('saved')));}
function lanterns(target){const wrap=el('div','lanterns');let n=0;regions.forEach(r=>{const b=button('✦','lantern',()=>{b.disabled=true;b.classList.add('on');n++;tone(n,.5);if(n===6){confetti();win();}});b.setAttribute('aria-label',tr(r.name));wrap.append(b);});target.append(wrap);}
function journal(main){const grid=el('div','collection');regions.forEach((r,i)=>{const won=lightCount(state)>i,c=el('article',`collect-card ${won?'':'locked'}`);c.append(el('div','object',won?r.gift:'◇'),el('h3','',r.name),el('p','',won?r.restored:text('Un recuerdo te espera aquí.','A keepsake is waiting here.')));grid.append(c);});main.append(grid,el('p','save-note',`${completedCount(state)}/48 ${tr(text('misiones terminadas','quests completed'))} · ${totalStars(state)}/144 ${t('stars')} · ${state.discovered.length}/6 ${tr(text('conchas secretas','secret shells'))}`));if(completedCount(state)>0){const list=el('div','quest-list');quests.filter(q=>state.completed[q.id]).slice(-8).reverse().forEach(q=>{const b=button('','quest-row',()=>startQuest(q));b.append(el('span','',q.name),el('small','', '★'.repeat(state.completed[q.id])+' ↻'));list.append(b);});main.append(el('h2','',text('Tus últimos pasos','Your latest footsteps')),list);}}
function cottage(main){const house=el('div',`cottage palette-${state.palette}`);house.append(el('h2','',text('Un lugar para tus tesoros','A home for your treasures')),el('p','',text('Cada luz trae un recuerdo de un amigo.','Each light brings a keepsake from a friend.')));const shelf=el('div','shelf');regions.forEach((r,i)=>shelf.append(el('span','',i<lightCount(state)?r.gift:'·')));house.append(shelf,el('p','',`🐚 ${state.discovered.length} ${tr(text('conchas de luz','starlight shells'))}`));main.append(house);const palettes=el('div','palette');for(let i=0;i<4;i++){const b=button('',state.palette===i?'active':'',()=>{state.palette=i;save();render();});b.setAttribute('aria-label',tr([text('Verde hoja','Leaf green'),text('Azul mar','Ocean blue'),text('Rosa flor','Blossom pink'),text('Lila noche','Evening lilac')][i]));b.setAttribute('aria-pressed',String(state.palette===i));palettes.append(b);}main.append(palettes,el('p','save-note',text('Toca un color para pintar tu casita.','Tap a color to paint your cottage.')));}
function ending(){const section=el('main','celebration');section.append(el('div','trophy','🌟'),el('p','eyebrow',text('FIN · Y UN NUEVO COMIENZO','THE END · AND A NEW BEGINNING')),el('h1','',t('final')),el('p','',t('finaltext')),el('div','earned','✦ ✦ ✦ ✦ ✦ ✦'),el('p','',`${totalStars(state)} / 144 ${t('stars')} · ${tr(text('Guardián de la Isla','Island Guardian'))}`),button(t('back'),'primary',()=>{screen='map';render();}),button(t('studio'),'soft',()=>{screen='studio';render();}));app.append(section);confetti();joy.effect('finish');}
// Save on every meaningful action. An interrupted activity resumes at its last completed stage.
save();render();
