/* One world, six story chapters, eight quests per chapter. ES is the default. */
export const text = (es,en) => ({es,en});
export const regions = [
 {id:'harbor',icon:'⛵',xy:[24,76],color:'#eeb17c',name:text('Puerto del Sol','Sunbeam Harbor'),friend:'Pip',animal:'🦊',gift:'🧭',intro:text('Soy Pip. La tormenta apagó el faro. Sus seis luces se perdieron. ¿Me ayudas a encontrarlas?','I’m Pip. The storm put out our lighthouse. Its six lights are lost. Will you help me find them?'),outro:text('¡Los barcos pueden volver! La primera luz estaba en tu forma de ayudar. Vamos al mercado.','The boats can come home! The first light was hiding in your helpful heart. Let’s visit the market.'),restored:text('Los barcos vuelven a casa.','The boats are coming home.')},
 {id:'market',icon:'🍊',xy:[27,48],color:'#d7a253',name:text('Valle Mandarina','Tangerine Valley'),friend:'Mila',animal:'🐰',gift:'🧺',intro:text('Mi huerto está lleno, pero el mercado está vacío. Juntos podemos preparar una gran merienda.','My orchard is full, but the market is empty. Together we can make a wonderful picnic.'),outro:text('¡Hay comida para todos! Nuestra luz de cuidado ya brilla. Oigo algo en la selva…','There’s food for everyone! Our light of care is shining. I hear something in the jungle…'),restored:text('El mercado celebra una merienda.','The market is having a picnic.')},
 {id:'jungle',icon:'🌿',xy:[29,25],color:'#81bca0',name:text('Selva Susurro','Whispering Wilds'),friend:'Ollie',animal:'🦥',gift:'🌱',intro:text('El río está quieto. Las luciérnagas se escondieron. Mira con calma: la selva deja pistas.','The river is still. The fireflies are hiding. Look closely: the jungle leaves clues.'),outro:text('¡El río canta otra vez! Las luciérnagas nos guían hasta el pueblo de la música.','The river sings again! The fireflies are showing us the way to the music village.'),restored:text('El río y las luciérnagas regresaron.','The river and fireflies are back.')},
 {id:'music',icon:'🎵',xy:[72,35],color:'#af9bd0',name:text('Pueblo Melodía','Melody Village'),friend:'Luna',animal:'🐱',gift:'🎸',intro:text('El viento se llevó nuestra canción. ¿Puedes escuchar, recordar y crear una nueva?','The wind carried away our song. Can you listen, remember, and make a new one?'),outro:text('¡Qué canción tan bonita! Hasta las flores del jardín quieren bailar.','What a lovely song! Even the garden flowers want to dance.'),restored:text('La plaza vuelve a tener música.','Music fills the square again.')},
 {id:'garden',icon:'🌸',xy:[75,71],color:'#d799ac',name:text('Jardín Corazón','Heartwood Garden'),friend:'Sol',animal:'🐻',gift:'🪞',intro:text('El espejo se nubló. No necesita magia: necesita palabras amables y amigos que se cuidan.','The mirror is cloudy. It doesn’t need magic. It needs kind words and friends who care.'),outro:text('¡El espejo brilla! Ser valiente también es pedir ayuda. La última luz está en la montaña.','The mirror shines! Being brave means asking for help, too. The last light is on the mountain.'),restored:text('El jardín florece con amistad.','Friendship makes the garden bloom.')},
 {id:'summit',icon:'✦',xy:[53,19],color:'#d8c888',name:text('Faro de las Estrellas','Starlight Summit'),friend:'Pip',animal:'🦊',gift:'👑',intro:text('Llegamos. Cada amigo trajo algo. Usemos todo lo que aprendimos para encender el faro.','We made it. Every friend brought something. Let’s use everything we learned to light the lighthouse.'),outro:text('¡Lo logramos! La isla brilla porque la cuidamos juntos. Este siempre será tu hogar de aventuras.','We did it! The island shines because we cared for it together. This will always be your adventure home.'),restored:text('El faro ilumina toda la isla.','The lighthouse shines across the island.')}
];
const names = [
 [['Una carta del mar','A letter from the sea'],['Ruedas listas','Wheels ready'],['El puente roto','The broken bridge'],['Luz roja, luz verde','Red light, green light'],['Carga para el barco','Cargo for the boat'],['La ruta de Pip','Pip’s route'],['Entrega especial','Special delivery'],['La luz del valor','The light of courage']],
 [['La cesta de Mila','Mila’s basket'],['Palabras del huerto','Orchard words'],['Monedas contadas','Counting coins'],['Una compra sabia','A wise purchase'],['Receta de amigos','A recipe for friends'],['Semillas para mañana','Seeds for tomorrow'],['El gran mercado','Market day'],['La luz del cuidado','The light of care']],
 [['Huellas pequeñas','Little footprints'],['Amigos escondidos','Hidden friends'],['El viaje de una gota','A drop’s journey'],['El puente de hojas','The leaf bridge'],['Guardianes del río','River guardians'],['El bosque recuerda','The forest remembers'],['Sigue las luciérnagas','Follow the fireflies'],['La luz de la curiosidad','The light of wonder']],
 [['Tres notas perdidas','Three lost notes'],['El tambor dormido','The sleeping drum'],['Palabras que bailan','Dancing words'],['Eco en la cueva','Echo in the cave'],['Rimas en el viento','Rhymes in the wind'],['La banda de Luna','Luna’s band'],['Nuestra canción','Our song'],['La luz de la alegría','The light of joy']],
 [['El espejo nublado','The cloudy mirror'],['Una mano amiga','A helping hand'],['Raíces y caminos','Roots and routes'],['Palabras valientes','Brave words'],['La mesa de todos','A table for everyone'],['Recuerdos bonitos','Lovely memories'],['El jardín florece','The garden blooms'],['La luz de la amistad','The light of friendship']],
 [['Mochila lista','Pack your bag'],['El sendero alto','The high trail'],['Piedras que cantan','Singing stones'],['El último puente','The last bridge'],['Un plan juntos','A plan together'],['Seis luces','Six lights'],['La puerta del faro','The lighthouse door'],['La noche de las estrellas','The night of stars']]
];
export const quests=regions.flatMap((r,ri)=>names[ri].map((n,i)=>({id:`${r.id}-${i}`,region:ri,index:i,name:text(...n)})));
const choice=(prompt,options,correct=0,hint=text('Mira otra vez. Tú puedes.','Look again. You can do this.'),scene='')=>({type:'choice',prompt,options:options.map(x=>typeof x==='string'?text(x,x):x),correct,hint,scene});
const order=(prompt,items)=>({type:'order',prompt,items});
const memory=(n)=>({type:'memory',pairs:n,prompt:text('Encuentra las parejas.','Find the matching pairs.')});
const tune=(n,seed)=>({type:'tune',notes:Array.from({length:n},(_,i)=>(seed+i*i+i)%5),prompt:text('Escucha. Luego toca las mismas notas.','Listen. Then tap the same notes.')});
const spell=(word,emoji)=>({type:'spell',word,scene:emoji,prompt:text('Forma esta palabra en inglés.','Build this English word.')});
const math=(n,i)=>{let a=2+n,b=2+(i%5),op=i%3;return choice(text(op===0?`Hay ${a} cajas con ${b} conchas. ¿Cuántas conchas?`:op===1?`Tenemos ${a+b} semillas. Plantamos ${b}. ¿Cuántas quedan?`:`Llevamos ${a} frutas y ${b} más. ¿Cuántas hay?`,op===0?`${a} boxes hold ${b} shells each. How many shells?`:op===1?`We have ${a+b} seeds. We plant ${b}. How many are left?`:`We carry ${a} fruits and ${b} more. How many now?`),[String(op===0?a*b:op===1?a:a+b),String(op===0?a+b+1:op===1?a+b:a+b+2),String(op===0?a*b+2:op===1?b+1:a+b-1)].filter((v,i,a)=>a.indexOf(v)===i),0,text(op===0?`${a} grupos de ${b}. Cuenta de ${b} en ${b}.`:op===1?`Empieza en ${a+b}. Quita ${b}.`:`Empieza en ${a}. Añade ${b}.`,op===0?`${a} groups of ${b}. Count by ${b}s.`:op===1?`Start at ${a+b}. Take away ${b}.`:`Start at ${a}. Add ${b}.`),op===0?'📦 '.repeat(a):'🌱');};
const food=[['APPLE','🍎'],['BANANA','🍌'],['CARROT','🥕'],['GRAPE','🍇'],['BREAD','🍞'],['MILK','🥛'],['EGG','🥚'],['RICE','🍚'],['PEAR','🍐'],['CORN','🌽'],['BEANS','🫘'],['FISH','🐟'],['MANGO','🥭'],['LEMON','🍋'],['WATER','💧'],['TOMATO','🍅'],['POTATO','🥔'],['CHEESE','🧀'],['ORANGE','🍊'],['AVOCADO','🥑']];
const nature=[
 ['¿Qué necesita una semilla?','What does a seed need?',['Agua y luz','Water and light'],['Solo piedras','Only stones'],['Una caja cerrada','A closed box'],'🌱'],
 ['¿Cuál animal es un mamífero?','Which animal is a mammal?',['Delfín','Dolphin'],['Mariposa','Butterfly'],['Rana','Frog'],'🐬'],
 ['¿Qué mueve un molino?','What moves a windmill?',['El viento','Wind'],['La tierra quieta','Still earth'],['La luna','The moon'],'🌬️'],
 ['¿Qué ayuda a las flores?','What helps flowers?',['Abejas que llevan polen','Bees carrying pollen'],['Basura en el suelo','Litter on the ground'],['Arrancar sus hojas','Pulling off their leaves'],'🐝'],
 ['¿Dónde vive un pez?','Where does a fish live?',['En el agua','In water'],['En una nube','In a cloud'],['En un nido','In a nest'],'🐟'],
 ['¿Qué hacemos con la basura?','What do we do with litter?',['Ponerla en su recipiente','Put it in its bin'],['Tirarla al río','Throw it in the river'],['Dejarla en el camino','Leave it on the path'],'♻️'],
 ['¿Qué debes hacer si ves fuego?','What should you do if you see a fire?',['Alejarme y avisar a un adulto','Move away and tell an adult'],['Tocarlo','Touch it'],['Acercar hojas','Put leaves near it'],'🔥'],
 ['¿Qué animal sale de una oruga?','What animal grows from a caterpillar?',['Mariposa','Butterfly'],['Pez','Fish'],['Gato','Cat'],'🦋']
];
const kindness=[
 ['No me sale todavía. ¿Qué puedo decir?','I can’t do it yet. What can I say?',['Puedo practicar','I can practice'],['Nunca podré','I will never learn'],['No vale la pena','It is not worth trying'],'🪞'],
 ['Pip está triste. ¿Qué haces?','Pip is sad. What do you do?',['Escucho y le acompaño','Listen and stay with him'],['Me río de él','Laugh at him'],['Le quito su juguete','Take his toy'],'🦊'],
 ['Tu amigo dice que no quiere un abrazo.','Your friend says they do not want a hug.',['Respeto su no','Respect their no'],['Lo abrazo igual','Hug them anyway'],['Me enojo con él','Get angry with them'],'💛'],
 ['Te equivocaste. ¿Y ahora?','You made a mistake. What now?',['Respiro y vuelvo a intentar','Breathe and try again'],['Soy un desastre','I am a disaster'],['Rompo todo','Break everything'],'🌸'],
 ['Hay mucho que llevar a la mesa.','There is a lot to carry to the table.',['Compartimos el trabajo','Share the work'],['Mando a todos','Boss everyone around'],['Escondo los platos','Hide the plates'],'🍽️'],
 ['Algo te preocupa. ¿Qué puedes hacer?','Something worries you. What can you do?',['Hablar con un adulto de confianza','Talk to a trusted adult'],['Guardarlo siempre','Keep it secret forever'],['Culpar a un amigo','Blame a friend'],'🌻'],
 ['Dos amigos quieren el mismo juguete.','Two friends want the same toy.',['Tomar turnos','Take turns'],['Gritar más fuerte','Shout louder'],['Romper el juguete','Break the toy'],'🧸'],
 ['Tu amiga ganó. ¿Qué le dices?','Your friend won. What do you say?',['¡Bien hecho!','Well done!'],['No te hablo','I will not talk to you'],['Eso no cuenta','That does not count'],'🏆']
];
const bank=(rows,i)=>{const r=rows[i%rows.length];return choice(text(r[0],r[1]),r.slice(2,5).map(x=>text(...x)),0,text('Piensa en lo que ayuda.','Think about what helps.'),r[5]);};
const money=(i)=>choice(text(`Tienes ${6+i} monedas. La fruta cuesta ${2+i}. ¿Cuánto queda?`,`You have ${6+i} coins. Fruit costs ${2+i}. How many are left?`),['4','3','5'],0,text(`Quita ${2+i} de ${6+i}.`,`Take ${2+i} away from ${6+i}.`),'🪙');
const geography=(i)=>[
 choice(text('¿Qué país tiene una hoja de arce en su bandera?','Which country has a maple leaf on its flag?'),['Canada','Panama','Trinidad & Tobago'],0,text('Su bandera es roja y blanca.','Its flag is red and white.'),'🍁'),
 choice(text('¿Dónde está el canal que une dos océanos?','Where is the canal that joins two oceans?'),['Panama','Canada','Trinidad & Tobago'],0,text('Está en América Central.','It is in Central America.'),'🚢'),
 choice(text('¿Dónde nació el steelpan?','Where was the steelpan born?'),['Trinidad & Tobago','Canada','Panama'],0,text('Son dos islas del Caribe.','It is a two-island Caribbean country.'),'🥁')
][i%3];
export function challenges(q){const i=q.index,r=q.region;
 if(r===0)return [math(1+Math.floor(i/3),i),i%2?{type:'drive',length:4+Math.floor(i/2),prompt:text('Lleva la carga. Avanza solo con luz verde.','Deliver the cargo. Move only on green.')}:order(text('Construye el puente de menor a mayor.','Build the bridge from smallest to largest.'),[i+1,i+3,i+5,i+7].map(n=>text(String(n),String(n)))),i%2?math(2+Math.floor(i/3),i+1):memory(3+Math.floor(i/3))];
 if(r===1)return [spell(...food[i*2]),money(i),i%2?spell(...food[i*2+1]):choice(text('Ahorro para semillas. ¿Qué compro primero?','I am saving for seeds. What should I buy first?'),[text('Las semillas','The seeds'),text('Otro juguete','Another toy'),text('Una bolsa vacía','An empty bag')],0,text('Recuerda tu meta.','Remember your goal.'),'🌱')];
 if(r===2)return [bank(nature,i),memory(3+Math.floor(i/3)),i%2?order(text('Ordena la vida de la mariposa.','Put the butterfly’s life in order.'),[text('Huevo','Egg'),text('Oruga','Caterpillar'),text('Crisálida','Chrysalis'),text('Mariposa','Butterfly')]):order(text('Ayuda a crecer a la planta.','Help the plant grow.'),[text('Plantar semilla','Plant seed'),text('Regar','Water'),text('Ver brote','See sprout'),text('Cosechar fruto','Pick fruit')])];
 if(r===3)return [tune(3+Math.floor(i/3),i),i%2?{type:'rhythm',pattern:[0,1,0,i%3,1,0],prompt:text('Sigue los golpes. Luego toca el patrón.','Follow the beats. Then tap the pattern.')}:choice(text('¿Qué palabra rima con gato?','Which word rhymes with cat?'),[text('Pato','Hat'),text('Luna','Moon'),text('Flor','Tree')],0,text('Escucha el final de cada palabra.','Listen to the end of each word.'),'🗣️'),i===6?{type:'studio',prompt:text('Crea la canción de nuestra isla.','Create our island song.')} :order(text('Lee el trabalenguas. Luego ordénalo.','Read the tongue twister. Then put it in order.'),[text('Pablito','Peter'),text('clavó','Piper'),text('un','picked'),text('clavito','peppers')])];
 if(r===4)return [bank(kindness,i),geography(i),i%2?memory(4+Math.floor(i/4)):bank(kindness,(i+3)%8)];
 return [i%2?math(4+Math.floor(i/2),i):spell(...food[16+i%4]),i%3===0?tune(5,i):i%3===1?{type:'drive',length:7,prompt:text('Lleva la última luz al faro.','Bring the last light to the lighthouse.')} :memory(5),i===7?{type:'lantern',prompt:text('Toca cada luz. Enciende nuestro faro.','Tap every light. Light our lighthouse.')} :i%2?bank(kindness,i):bank(nature,i)];
}
export const ui={
 title:text('Isla Aventura','Island Adventure'),subtitle:text('La luz perdida','The Lost Light'),map:text('La isla','The island'),journal:text('Mi aventura','My adventure'),home:text('Mi casita','My cottage'),studio:text('Crear música','Make music'),play:text('¡Vamos, Pip!','Let’s go, Pip!'),continue:text('Seguir la aventura','Continue adventure'),next:text('Siguiente','Next'),back:text('Volver a la isla','Back to the island'),listen:text('Escuchar','Listen'),help:text('Cómo jugar','How to play'),sound:text('Sonido','Sound'),saved:text('Tu aventura se guarda en este navegador.','Your adventure saves in this browser.'),nosave:text('No se puede guardar aquí. Mantén esta pestaña abierta.','Saving is unavailable here. Keep this tab open.'),quest:text('Misión','Quest'),chapter:text('Capítulo','Chapter'),lights:text('luces','lights'),stars:text('estrellas','stars'),found:text('Encontrado','Found'),retry:text('Otra vez','Try again'),correct:text('¡Correcto, lo lograste!','Correct, you got it!'),wrong:text('Incorrecto. Intenta otra vez.','Incorrect. Try again.'),done:text('¡Misión cumplida!','Quest complete!'),prize:text('Un recuerdo para tu casita','A keepsake for your cottage'),locked:text('Recupera la luz anterior para abrir este lugar.','Find the previous light to open this place.'),replay:text('Jugar otra vez','Play again'),choose:text('Toca un lugar para explorar.','Tap a place to explore.'),helptext:text('1. Sigue la estrella dorada.\n2. Ayuda a un amigo con tres retos.\n3. Gana recuerdos y recupera las seis luces.\nPuedes parar y volver cuando quieras. No hay vidas que perder.','1. Follow the golden star.\n2. Help a friend with three challenges.\n3. Earn keepsakes and find the six lights.\nYou can stop and come back anytime. There are no lives to lose.'),close:text('Cerrar','Close'),chapterDone:text('¡Una luz volvió a brillar!','A light is shining again!'),final:text('La isla vuelve a brillar','The island shines again'),finaltext:text('Cada puente, canción y gesto amable nos trajo hasta aquí. Recuperaste las seis luces. Ahora puedes explorar, crear canciones y volver a tus lugares favoritos.','Every bridge, song, and kind act brought us here. You found all six lights. Now explore, make songs, and revisit your favorite places.')
};
