(() => {
  if (location.pathname.replace(/\/+$/, '/') !== '/games/traffic-town/' || window.TrafficTownLevelTwoLoaded) return;
  window.TrafficTownLevelTwoLoaded = true;

  let idx = 0, score = 0, deck = [];
  const qs = [
    { q:'Heavy rain starts. What should you do?', a:['Slow down','Speed up','Close eyes'], good:0, why:'Rain means slower, safer driving.' },
    { q:'A school bus stops. What is safest?', a:['Stop and wait','Race around it','Honk nonstop'], good:0, why:'Kids may be crossing.' },
    { q:'You need to park in a tight spot.', a:['Go slow and line up','Crash in fast','Ignore lines'], good:0, why:'Slow control makes parking safe.' },
    { q:'Fuel is low. Pick the best fuel.', a:['Healthy snack','Candy pile','Empty tank'], good:0, why:'Healthy food = better fuel.' },
    { q:'Traffic jam ahead. What helps?', a:['Be patient','Bump cars','Quit driving'], good:0, why:'Patience keeps the town safe.' },
    { q:'Night driving. What do you need?', a:['Headlights','No looking','Drive faster'], good:0, why:'Lights help you see.' }
  ];

  const css = document.createElement('style');
  css.textContent = `.tt-l2{position:fixed;inset:0;background:rgba(16,20,54,.74);z-index:21000;display:flex;align-items:center;justify-content:center;padding:14px;font-family:Arial,sans-serif}.tt-l2-card{width:min(620px,100%);background:linear-gradient(180deg,#fff6e6,#e8fbff);border:5px solid #101436;border-radius:30px;padding:16px;box-shadow:0 18px 0 rgba(0,0,0,.32);color:#101436}.tt-l2-title{text-align:center;font-size:30px;font-weight:900;background:#ffc83d;border:4px solid #101436;border-radius:20px;padding:12px}.tt-l2-road{height:96px;background:#353a47;border:5px solid #101436;border-radius:22px;margin:12px 0;position:relative;overflow:hidden}.tt-l2-road:before{content:'';position:absolute;left:0;right:0;top:45px;height:8px;background:repeating-linear-gradient(90deg,#fff 0 44px,transparent 44px 78px);animation:ttDash .55s linear infinite}.tt-l2-car{position:absolute;left:42%;top:20px;font-size:50px;animation:ttDrive .7s infinite}.tt-l2-q{font-size:26px;line-height:1.08;font-weight:900;text-align:center;background:#fff;border:4px solid #101436;border-radius:22px;padding:15px}.tt-l2-answers{display:grid;gap:10px;margin-top:12px}.tt-l2-btn{border:4px solid #101436;border-radius:20px;padding:16px 14px 16px 58px;font-size:21px;font-weight:900;text-align:left;background:#fffdf6;color:#101436;box-shadow:0 7px 0 #101436;position:relative}.tt-l2-btn:before{content:attr(data-label);position:absolute;left:13px;top:50%;transform:translateY(-50%);width:32px;height:32px;border:3px solid #101436;border-radius:50%;background:#ffc83d;display:flex;align-items:center;justify-content:center}.tt-l2-btn:nth-child(2){background:#b8f2ff}.tt-l2-btn:nth-child(3){background:#d7b9ff}.tt-l2-btn.good{background:#7dffb0!important}.tt-l2-btn.bad{background:#ff3d3d!important;color:#fff!important}.tt-l2-note{font-size:18px;font-weight:900;background:#f1fff3;border:3px solid #34d17a;border-radius:16px;margin-top:12px;padding:10px;text-align:center}.tt-l2-actions{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:12px}.tt-l2-actions button{border:4px solid #101436;border-radius:18px;padding:13px 8px;font-size:17px;font-weight:900;background:#ffc83d;box-shadow:0 6px 0 rgba(0,0,0,.22)}@keyframes ttDash{to{background-position:-78px 0}}@keyframes ttDrive{50%{transform:translateY(-5px)}}@media(max-width:430px){.tt-l2-title{font-size:24px}.tt-l2-q{font-size:22px}.tt-l2-btn{font-size:18px}.tt-l2-actions{grid-template-columns:1fr}}`;
  document.head.appendChild(css);

  function shuffle(a){return a.map(v=>({v,r:Math.random()})).sort((x,y)=>x.r-y.r).map(x=>x.v)}
  function sound(n){try{if(window.SeanGameSounds&&SeanGameSounds[n])SeanGameSounds[n]()}catch(e){}}
  function speak(t){try{if(window.SeanGameVoice&&SeanGameVoice.speak)SeanGameVoice.speak(t)}catch(e){}}

  function start(){idx=0;score=0;deck=shuffle(qs);document.querySelector('.tt-l2')?.remove();const w=document.createElement('div');w.className='tt-l2';w.innerHTML='<div class="tt-l2-card"><div class="tt-l2-title">🚗 Traffic Town · Level 2</div><div class="tt-l2-road"><div class="tt-l2-car">🚗</div></div><div class="tt-l2-q"></div><div class="tt-l2-answers"></div><div class="tt-l2-note">Medium mode: drive safer in trickier town moments.</div><div class="tt-l2-actions"><button class="again">🔁 Play Again</button><button class="menu">🏠 Main Menu</button><button class="close">✕ Close</button></div></div>';document.body.appendChild(w);w.querySelector('.again').onclick=start;w.querySelector('.menu').onclick=()=>location.href='/games/';w.querySelector('.close').onclick=()=>w.remove();render();sound('levelUp')}
  function render(){const w=document.querySelector('.tt-l2');if(!w)return;if(idx>=deck.length)return finish();const it=deck[idx];w.querySelector('.tt-l2-q').textContent='Step '+(idx+1)+' of '+deck.length+': '+it.q;w.querySelector('.tt-l2-note').textContent='Look at the road problem. Choose the safest move.';const ans=shuffle(it.a.map((text,i)=>({text,ok:i===it.good})));w.querySelector('.tt-l2-answers').innerHTML=ans.map((a,i)=>'<button class="tt-l2-btn" data-label="'+String.fromCharCode(65+i)+'">'+a.text+'</button>').join('');w.querySelectorAll('.tt-l2-btn').forEach((b,i)=>b.onclick=()=>pick(b,ans[i],it))}
  function pick(btn,a,it){const w=document.querySelector('.tt-l2');w.querySelectorAll('.tt-l2-btn').forEach(b=>b.disabled=true);if(a.ok){score+=10;btn.classList.add('good');w.querySelector('.tt-l2-note').textContent=it.why;sound('correct');speak('Correct, you got it!');setTimeout(()=>{idx++;render()},1000)}else{btn.classList.add('bad');w.querySelector('.tt-l2-note').textContent='Incorrect. Try again.';sound('wrong');speak('Incorrect.');setTimeout(()=>{w.querySelectorAll('.tt-l2-btn').forEach(b=>{b.disabled=false;b.classList.remove('bad')})},800)}}
  function finish(){const w=document.querySelector('.tt-l2');w.querySelector('.tt-l2-q').textContent='🏆 Medium Driver Badge earned!';w.querySelector('.tt-l2-answers').innerHTML='';w.querySelector('.tt-l2-note').textContent='Traffic Town Level 2 complete · Score '+score;sound('levelUp')}
  window.addEventListener('seanGameNextLevelRequest',start);
  window.TrafficTownLevelTwoStart=start;
})();
